### ISSUE TITLE
Bug: Settings - Default theme throws an error when opening codeblock header section.

### ISSUE THREAD

**Issue by KleinByte** [mayurankv/Obsidian-Code-Styler#209]
When opening the settings and navigating to the Codeblock Header section with default theme on. Most of the header customization options don't render and an error is thrown in the console about a color having an incorrect format.

Edit:
- I had css snippets turned on, when turning off css snippets, the error disappeared.  No issue with the plugin itself, but possibly need better handling of errors like this to prevent parts of the customization options from not rendering.

Error:

```
plugin:code-styler:4010 Uncaught Error: The provided string color doesn't have a correct format
    at eval (plugin:code-styler:4010:13)
    at ut (plugin:code-styler:4012:4)
    at n2.toHEXAObject (plugin:code-styler:4308:14)
    at n2.toHEXA (plugin:code-styler:4311:21)
    at getCssVariable (plugin:code-styler:5479:17)
    at getColour (plugin:code-styler:5464:31)
    at new PickrResettable (plugin:code-styler:5417:16)
    at SettingsTab.createPickr (plugin:code-styler:5333:19)
    at eval (plugin:code-styler:4823:12)
    at e.then (app.js:1:1317359)
    at SettingsTab.generateCodeblockHeaderSettings (plugin:code-styler:4822:8)
    at SettingsTab.generateCodeblockSetting (plugin:code-styler:4543:12)
    at SettingsTab.displayCodeblockSettings (plugin:code-styler:4499:10)
    at SettingsTab.generateSettings (plugin:code-styler:4526:12)
    at SettingsTab.display (plugin:code-styler:4477:10)
    at t.openTab (app.js:1:2755382)
    at t.eval (plugin:settings-search:288:23)
    at t.wrapper [as openTab] (plugin:settings-search:59:20)
    at HTMLDivElement.<anonymous> (app.js:1:2753821)
```

**Comment by mayurankv** [comment]
Ahh can you let me know what the snippet included? It would have been to do with a colour definition. Yes I agree on error handling, I'll make a new issue for it.

**Comment by mayurankv** [comment]
Thanks for the report!

**Comment by mayurankv** [comment]
Hi, I'm going to close this issue as I've created a specific one for improved error handling but if you provide me with the snippet that broke it I can try and make that compatible as well!
