### ISSUE TITLE
Bug: Functional Issues in Source Mode and Live Preview 

### ISSUE THREAD

**Issue by RedAlien00** [mayurankv/Obsidian-Code-Styler#291]
Functional Issues in Source Mode and Live Preview - Click, Edit, and Expand Features Not Working Properly

## Describe the bug
1. Works well in Reading Mode.
2. Not clickable or expandable in Source Mode/Live Preview.

Is it a CSS bug or incorrect application or something else? : obviously, Code-Styler plugin issue

### Steps to reproduce
1. Have you tried another theme/disabling CSS snippets? : Yes

### Environment
- Plugin Version: 1.1.7
- Obsidian Version:  1.7.5
- Platform:  Desktop
- OS:  MacOS M1 Ventura
- Theme:  Things
- CSS Snippets:  Yes

### Screenshots

https://github.com/user-attachments/assets/4bd1421d-17da-484d-845f-8120b682f7e1

### Additional context
Uncaught Error: Ranges must be added sorted by `from` position and `startSide`
    at e.addInner (app.js:1:297087)
    at e.add (app.js:1:296861)
    at buildLineDecorations (plugin:code-styler:19666:15)
    at e.update [as updateF] (plugin:code-styler:19447:14)
    at Object.update (app.js:1:275169)
    at e.computeSlot (app.js:1:286019)
    at Ve (app.js:1:279113)
    at new e (app.js:1:284988)
    at e.applyTransaction (app.js:1:285974)
    at e.get (app.js:1:281117)

**Comment by mayurankv** [comment]
This will be fixed in the upcoming update. Sorry!
